spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postitus
    username: postgres
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
